### ISSUE TITLE
Typo in table5

### ISSUE THREAD

**Issue by developer0hye** [yuhuixu1993/BNET#3]
![image](https://user-images.githubusercontent.com/35001605/117996935-88108500-b37d-11eb-864c-4949c51ba4ed.png)

Thanks for sharing your work!

In the table 5, it seems that the order of Ap{s, m, l} is written in reverse order.

**Comment by yuhuixu1993** [comment]
> ![image](https://user-images.githubusercontent.com/35001605/117996935-88108500-b37d-11eb-864c-4949c51ba4ed.png)
> 
> Thanks for sharing your work!
> 
> In the table 5, it seems that the order of Ap{s, m, l} is written in reverse order.

Thanks for the notice, I will update the revised version soon.
